@CredentialValidator_HostAddress = http://localhost:5155

### Test credentials (expect 200 OK)
POST {{CredentialValidator_HostAddress}}/api/CredentialValidator/authenticate
Content-Type: application/json
{
  "username": "CharlieGo_",
  "password": "randomstring2025",
  "email": "perry@platipus.com",
  "certificatestring": "##';q]w[e19023i909oipqwjkdmlaslmk12i31jh912ihenoqlkdasm]QW"

}